routes/web.php
<?php

use Illuminate\Support\Facades\Route;

$this->settingRole = config("settings.role");

// Route::group([
//     "namespace" => "Home",
//     "as" => "home.",
// ], function () {
//     Route::group([
//         "namespace" => "Dashboards"
//     ], function () {
//         Route::resource("dashboards", "DashboardController")->only(["index"]);
//         Route::group([
//             "as" => "dashboards.",
//         ], function () {
//             Route::get("index", "DashboardController@index")->name("index");
//             Route::get("", "DashboardController@index")->name("index");
//         });
//     });
// });

Route::namespace("Auth")->group(function () {
    Route::get("", "LoginController@showLoginForm")->name("home.dashboards.index");
    Route::get("login", 'LoginController@showLoginForm')->name("login");
    Route::post("login", 'LoginController@login')->name("login");
    Route::post("logout", 'LoginController@logout')->name("logout");
});

Route::middleware(["auth"])->group(function () {
    //Administrator
    Route::group([
        "middleware" => ["role:" . implode("|", $this->settingRole["administrator"])],
        "namespace" => "Administrator",
        "as" => "administrator.",
        "prefix" => "administrator"
    ], function () {
        Route::group([
            "namespace" => "Dashboards",
        ], function () {
            Route::resource("dashboards", "DashboardController")->only(["index"]);
            Route::group([
                "as" => "dashboards.",
            ], function () {
                Route::get("", "DashboardController@index")->name("index");
            });
        });

        Route::group([
            "namespace" => "Profiles",
            "as" => "profile.",
            "prefix" => "profile"
        ], function () {
            Route::get("index", "ProfileController@index")->name("index");
            Route::get("", "ProfileController@index")->name("index");
            Route::put("", "ProfileController@update")->name("update");
            Route::delete("", "ProfileController@destroy")->name("destroy");
            Route::put("password", "ProfileController@updatePassword")->name("update-password");
            Route::put("avatar", "ProfileController@updateAvatar")->name("update-avatar");
        });

        Route::group([
            "middleware" => ["role:" . $this->settingRole["administrator"]["superadmin"]],
        ], function () {
            Route::group([
                "namespace" => "Roles"
            ], function () {
                Route::resource("roles", "RoleController")->except(["show"]);
            });

            Route::group([
                "namespace" => "Permissions"
            ], function () {
                Route::resource("permissions", "PermissionController")->except(["show", "create", "edit"]);
            });
        });

        Route::group([
            "namespace" => "Users"
        ], function () {
            Route::resource("users", "UserController")->except(["show"]);
            Route::group([
                "as" => "users.",
                "prefix" => "users"
            ], function () {
                Route::put("{id}/password", "UserController@updatePassword")->name("update-password");
                Route::put("{id}/status", "UserController@updateStatus")->name("update-status");
                Route::put("{id}/avatar", "UserController@updateAvatar")->name("update-avatar");

                Route::group([
                    "as" => "deleted.",
                    "prefix" => "deleted"
                ], function () {
                    Route::get("index", "UserDeletedController@index")->name("index");
                    Route::get("", "UserDeletedController@index")->name("index");
                    Route::post("{id}/restore", "UserDeletedController@restore")->name("restore");
                });
            });
        });

        Route::group([
            "namespace" => "Variables"
        ], function () {
            Route::resource("variables", "VariableController")->except(["show"]);
        });

        Route::group([
            "namespace" => "Rules"
        ], function () {
            Route::resource("rules", "RuleController")->except(["show"]);
        });

        Route::group([
            "namespace" => "Executes"
        ], function () {
            Route::resource("executes", "ExecuteController")->except(["edit", "update"]);
        });
    });
});

app/Models/Variable.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Variable extends Model
{
    protected $fillable = [
        "name",
        "type",
        "column_name"
    ];

    public function assemblages()
    {
        return $this->hasMany(VariableAssemblage::class);
    }
}

app/Http/Controllers/Administrator/Dashboards/DashboardController.php
<?php

namespace App\Http\Controllers\Administrator\Dashboards;

use App\Http\Controllers\Controller;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;

use App\Models\Person;
use App\Models\Rule;
use App\Models\Variable;

class DashboardController extends Controller
{
    public function __construct()
    {
        $this->settingRole = config("settings.role");

        $this->middleware(function ($request, $next) {
            $this->authUser = auth()->user();
            return $next($request);
        });
    }

    public function index()
    {
        $variables = Variable::all();
        $rules = Rule::all();

        if ($this->authUser->hasRole($this->settingRole["administrator"]["superadmin"])) {
            $permissions = Permission::all();
            $roles = Role::all();
            $people = Person::withTrashed()->orderBy("full_name")->whereHas("user");

            $compact = compact("people", "permissions", "roles");
        } else {
            $people = Person::withTrashed()->orderBy("full_name")->whereHas("user.roles", function ($roles) {
                $roles->where("name", "!=", $this->settingRole["administrator"]["superadmin"]);
            });

            $compact = compact("people", "variables", "rules");
        }

        return view(
            "administrator.dashboards.index",
            $compact
        );
    }
}

app/Http/Controllers/Administrator/Executes/ExecuteController.php
<?php

namespace App\Http\Controllers\Administrator\Executes;

use App\Http\Controllers\Controller;
use App\Models\Rule;
use App\Models\RuleCondition;
use Illuminate\Http\Request;

use App\Models\Variable;

class ExecuteController extends Controller
{
    public function index()
    {
        return redirect()->route(
            "administrator.executes.create"
        );
    }

    public function create()
    {
        $variables = Variable::pluck("name", "id");
        $inputVariables = Variable::whereType("INPUT")->pluck("column_name", "id")->toArray();
        $outputVariables = Variable::whereType("OUTPUT")->pluck("name", "id")->toArray();
        $rules = Rule::all();

        if ($rules->count()) {
            return view(
                "administrator.executes.create",
                compact("variables", "inputVariables", "outputVariables")
            );
        } else {
            abort(404);
        }
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            "file" => "required|mimes:csv,txt",
            "multiplier_result" => "required|numeric",
            "decimal_digit" => "required|numeric",
        ]);

        if ($request->file("file")->getClientOriginalExtension() == "csv") {
            $csvFile = $request->file("file")->getPathname();

            $file = fopen($csvFile, "r");
            $data = $successData = $failedData = [];

            $inputVariables = Variable::whereType("INPUT");
            $outputVariables = Variable::whereType("OUTPUT")->first();
            $tempColumns = fgetcsv($file, 0, ",");
            if (is_array($tempColumns) && count($tempColumns) > $inputVariables->count() && $outputVariables) {
                $inputVariableColumnNames = $inputVariables->pluck("column_name")->toArray();
                $columns["variables"] = [];

                // Take the location of the variable column and separate it from other columns
                foreach ($tempColumns as $key => $tempColumn) {
                    $tempColumn = trim($tempColumn);
                    if ($tempColumn) {
                        if (in_array($tempColumn, $inputVariableColumnNames)) {
                            $columns["variables"][$tempColumn] = $key;
                        } else {
                            $columns["descriptions"][$tempColumn] = $key;
                        }
                    }
                }

                $file = fopen($csvFile, "r");
                $i = 0;
                while (!feof($file)) {
                    $textLine = fgetcsv($file, 0, ",");
                    if ($i > 0 && $textLine && count($textLine) > $inputVariables->count()) {
                        $data[$i] = [
                            "description" => "",
                            "variables" => []
                        ];

                        // Concatenate column contents that are not column variables
                        if ($columns["descriptions"]) {
                            $j = 0;
                            foreach ($columns["descriptions"] as $descriptionKey) {
                                $textLine[$descriptionKey] = trim($textLine[$descriptionKey]);
                                if ($textLine[$descriptionKey]) {
                                    $data[$i]["description"] .= $textLine[$descriptionKey];
                                    if ($j != count($columns["descriptions"]) - 1) {
                                        $data[$i]["description"] .= " - ";
                                    }
                                }
                                $j++;
                            }
                        }

                        if ($columns["variables"]) {
                            foreach ($columns["variables"] as $variableColumnName => $variableKey) {
                                $data[$i]["variables"][$variableColumnName] = [
                                    "input_value" => $textLine[$variableKey] ?? 0
                                ];

                                // Look for membership functions
                                $variable = Variable::whereColumnName($variableColumnName)->first();
                                $data[$i]["variables"][$variableColumnName]["assemblages"] = $variable->assemblages()->where([
                                    ["left_point_value", "<=", $textLine[$variableKey]],
                                    ['right_point_value', '>=', $textLine[$variableKey]]
                                ])->get()->keyBy("id")->toArray();

                                $data[$i]["variables"][$variableColumnName]["id"] = $variable->id;
                                $data[$i]["variables"][$variableColumnName]["name"] = $variable->name;
                                $data[$i]["variables"][$variableColumnName]["column_name"] = $variable->column_name;

                                // Calculate the implication value of each set of variables
                                $assemblages = $variable->assemblages()->get();
                                $implications = $data[$i]["variables"][$variableColumnName]["assemblages"];
                                foreach ($assemblages as $assemblage) {
                                    if (array_key_exists($assemblage->id, $data[$i]["variables"][$variableColumnName]["assemblages"])) {
                                        $inputValue =  $data[$i]["variables"][$variableColumnName]["input_value"];
                                        if ($assemblage->left_point_value <= $inputValue && $assemblage->left_midpoint_value >= $inputValue) {
                                            if ($assemblage->left_point_value == $assemblage->left_midpoint_value) {
                                                $implications[$assemblage->id]["value"] = 1;
                                            } else {
                                                $implications[$assemblage->id]["value"] = ($inputValue - $assemblage->left_point_value) / ($assemblage->left_midpoint_value - $assemblage->left_point_value);
                                            }
                                        } else if ($assemblage->left_midpoint_value <= $inputValue && $assemblage->right_midpoint_value >= $inputValue) {
                                            $implications[$assemblage->id]["value"] = 1;
                                        } else if ($assemblage->right_midpoint_value <= $inputValue && $assemblage->right_point_value >= $inputValue) {
                                            if ($assemblage->right_point_value == $assemblage->right_midpoint_value) {
                                                $implications[$assemblage->id]["value"] = 1;
                                            } else {
                                                $implications[$assemblage->id]["value"] = ($assemblage->right_point_value - $inputValue) / ($assemblage->right_point_value - $assemblage->right_midpoint_value);
                                            }
                                        } else {
                                            $implications[$assemblage->id]["value"] = 0;
                                        }
                                    }
                                }

                                $data[$i]["variables"][$variableColumnName]["assemblages"] = $implications;
                            }

                            // Create all possible rules from a variable set
                            $variables = $data[$i]["variables"];
                            $j = 0;
                            $assemblageIds = [];
                            foreach ($variables as $variableKey => $variable) {
                                $assemblageIdsTemporaries = [];
                                foreach ($variable["assemblages"] as $assemblage) {
                                    if ($j === 0) {
                                        $assemblageIds[] = [$assemblage["id"]];
                                    } else {
                                        foreach ($assemblageIds as $key => $assemblageId) {
                                            array_push($assemblageId, $assemblage["id"]);
                                            $assemblageIdsTemporaries[] = $assemblageId;
                                        }
                                    }
                                }

                                if ($j !== 0) {
                                    $assemblageIds = $assemblageIdsTemporaries;
                                }
                                $j++;
                            }

                            $rules = Rule::with(["assemblage.variable", "conditions.assemblage.variable"])->get();
                            $is_founded = false;
                            $multiplicationResult = $increaseInYield = 0;
                            foreach ($rules as $rule) {
                                // Look for rules that are already in the database
                                foreach ($assemblageIds as $assemblageId) {
                                    $ruleConditionsCountTemp = RuleCondition::whereRuleId($rule->id)->whereIn("variable_assemblage_id", $assemblageId)->count();
                                    if ($ruleConditionsCountTemp >= count($assemblageId)) {
                                        $ruleTemp = $rule->toArray();
                                        $is_founded = true;
                                    }
                                }

                                // If a rule is found
                                if ($is_founded) {
                                    $conditionValue = [];
                                    // Takes the implication value of each set of variables based on the found rules

app/Http/Controllers/Api/Variables/VariableController.php
<?php

namespace App\Http\Controllers\Api\Variables;

use App\Http\Controllers\Controller;
use App\Helpers\ResponseHelper;

use App\Models\Variable;

class VariableController extends Controller
{
    public function __construct()
    {
        $this->responHelper = new ResponseHelper;
    }

    public function index()
    {
        $variables = Variable::get();
        if ($variables->count()) {
            return $this->responHelper->successWithData($variables);
        } else {
            return $this->responHelper->errorNotFound();
        }
    }

    public function show($id)
    {
        $variable = Variable::with("assemblages")->find($id);
        if ($variable) {
            return $this->responHelper->successWithData($variable);
        } else {
            return $this->responHelper->errorNotFound();
        }
    }
}

resources/views/administrator/variables/create.blade.php
@extends('administrator.layouts.template')

@section('css')
<style>
    input::-webkit-outer-spin-button,
    input::-webkit-inner-spin-button {
        -webkit-appearance: none;
        margin: 0;
    }

    input[type=number] {
        -moz-appearance: textfield;
    }
</style>
@endsection

@section('content')
@if ($errors->all())
<div class="alert alert-danger alert-dismissible fade show mb-0" role="alert">
    <button type="button" class="close h-100" data-dismiss="alert" aria-label="Close" style="outline: none;">
        <span aria-hidden="true">×</span>
    </button>
    <i class="fa fa-info mx-2"></i>
    <strong>Something went wrong!</strong>
</div>
@endif

<div class="main-content-container container-fluid px-4">
    <!-- Page Header -->
    <div class="page-header row no-gutters mb-4"></div>
    <!-- End Page Header -->

    <div class="row">
        <div class="col">
            <div class="card card-small mb-4">
                <div class="card-header border-bottom">
                    <h6 class="m-0">Create Variable</h6>
                </div>
                <ul class="list-group list-group-flush">
                    <form method="POST" action="{{ route('administrator.variables.store') }}">
                        @csrf

                        <li class="list-group-item p-4">
                            <div class="row">
                                <div class="col-sm-6">
                                    <strong class="text-muted d-block mb-2">Name</strong>
                                    <div class="form-group">
                                        <input type="text" name="name" class="form-control @error('name') is-invalid @enderror" placeholder="Name" value="{{ old('name') }}" required>

                                        @error("name")
                                        <div class="invalid-feedback">{{ $message }}</div>
                                        @enderror
                                    </div>
                                </div>

                                <div class="col-sm-2">
                                    <strong class="text-muted d-block mb-2">Type</strong>
                                    <div class="form-group">
                                        {!! Form::select('type', [
                                        "INPUT" => "INPUT",
                                        "OUTPUT" => "OUTPUT",
                                        ], old('type'), [
                                        'class' => 'form-control' . ($errors->has('type') ? ' is-invalid' : '' ),
                                        'id' => 'type',
                                        'required' => 'required'
                                        ]) !!}

                                        @error("type")
                                        <div class="invalid-feedback">{{ $message }}</div>
                                        @enderror
                                    </div>
                                </div>

                                <div class="col-sm-4">
                                    <strong class="text-muted d-block mb-2">Column Name</strong>
                                    <div class="form-group">
                                        <input type="text" id="column-name" name="column_name" class="form-control @error('column_name') is-invalid @enderror" placeholder="Column Name" value="{{ old('column_name') }}" {{ old('type') == 'OUTPUT' ? 'disabled' : '' }}>

                                        @error("column_name")
                                        <div class="invalid-feedback">{{ $message }}</div>
                                        @enderror
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-sm-12">
                                    <strong class="text-muted d-block mb-2">Assemblages</strong>
                                    <div class="form-group">
                                        @if (old('assemblages') && is_array(old('assemblages')))
                                        @forelse(old('assemblages') as $assemblageKey => $assemblage)
                                        <div class="form-group mb-2" data-type="assemblages">
                                            <div class="input-group mb-2" data-id="{{ $assemblageKey }}">
                                                <input type="text" name="assemblages[{{ $assemblageKey }}][name]" class="form-control @error('assemblages.'.$assemblageKey.'.name') is-invalid @enderror" placeholder="Name" value="{{ $assemblage['name'] }}" required>
                                                <input type="number" step="any" min="0" name="assemblages[{{ $assemblageKey }}][left_point_value]" class="form-control text-right @error('assemblages.'.$assemblageKey.'.left_point_value') is-invalid @enderror" placeholder="Left Point Value" value="{{ $assemblage['left_point_value'] }}" required>
                                                <input type="number" step="any" min="0" name="assemblages[{{ $assemblageKey }}][left_midpoint_value]" class="form-control text-right @error('assemblages.'.$assemblageKey.'.left_midpoint_value') is-invalid @enderror" placeholder="Left Midpoint Value" value="{{ $assemblage['left_midpoint_value'] }}" required>
                                                <input type="number" step="any" min="0" name="assemblages[{{ $assemblageKey }}][right_midpoint_value]" class="form-control text-right @error('assemblages.'.$assemblageKey.'.right_midpoint_value') is-invalid @enderror" placeholder="Right Midpoint Value" value="{{ $assemblage['right_midpoint_value'] }}" required>
                                                <input type="number" step="any" min="0" name="assemblages[{{ $assemblageKey }}][right_point_value]" class="form-control text-right @error('assemblages.'.$assemblageKey.'.right_point_value') is-invalid @enderror" placeholder="Right Value" value="{{ $assemblage['right_point_value'] }}" required>

                                                <div class="input-group-append">
                                                    <button type="button" class="list-destroy-button btn btn-sm btn-danger">Destroy</button>
                                                </div>
                                            </div>
                                        </div>
                                        @empty
                                        <div class="form-group mb-2" data-type="assemblages">
                                            <div class="input-group mb-2" data-id="0">
                                                <input type="text" name="assemblages[0][name]" class="form-control" placeholder="Name" value="" required>
                                                <input type="number" step="any" min="0" name="assemblages[0][left_point_value]" class="form-control text-right" placeholder="Left Point Value" value="" required>
                                                <input type="number" step="any" min="0" name="assemblages[0][left_midpoint_value]" class="form-control text-right" placeholder="Left Midpoint Value" value="" required>
                                                <input type="number" step="any" min="0" name="assemblages[0][right_midpoint_value]" class="form-control text-right" placeholder="Right Midpoint Value" value="" required>
                                                <input type="number" step="any" min="0" name="assemblages[0][right_point_value]" class="form-control text-right" placeholder="Right Value" value="" required>

                                                <div class="input-group-append">
                                                    <button type="button" class="list-destroy-button btn btn-sm btn-danger">Destroy</button>
                                                </div>
                                            </div>
                                        </div>
                                        @endforelse
                                        @else
                                        <div class="form-group mb-2" data-type="assemblages">
                                            <div class="input-group mb-2" data-id="0">
                                                <input type="text" name="assemblages[0][name]" class="form-control" placeholder="Name" value="" required>
                                                <input type="number" step="any" min="0" name="assemblages[0][left_point_value]" class="form-control text-right" placeholder="Left Point Value" value="" required>
                                                <input type="number" step="any" min="0" name="assemblages[0][left_midpoint_value]" class="form-control text-right" placeholder="Left Midpoint Value" value="" required>
                                                <input type="number" step="any" min="0" name="assemblages[0][right_midpoint_value]" class="form-control text-right" placeholder="Right Midpoint Value" value="" required>
                                                <input type="number" step="any" min="0" name="assemblages[0][right_point_value]" class="form-control text-right" placeholder="Right Value" value="" required>

                                                <div class="input-group-append">
                                                    <button type="button" class="list-destroy-button btn btn-sm btn-danger">Destroy</button>
                                                </div>
                                            </div>
                                        </div>
                                        @endif

                                        <div class="mt-2 text-center">
                                            <button type="button" class="list-add-button btn btn-sm btn-success pt-1 pb-1 ">
                                                <i class="material-icons">add</i>
                                                Add Assemblage
                                            </button>
                                        </div>

                                        @error('assemblages.*')
                                        <input type="text" class="form-control is-invalid" hidden>
                                        <div class="invalid-feedback">Something went wrong!</div>
                                        @enderror
                                    </div>
                                </div>
                            </div>
                        </li>

                        <li class="list-group-item pt-3 pb-3 pl-4 pr-4 text-left">
                            <button type="submit" class="btn btn-sm btn-primary mt-1 mb-1 mr-2" style="width: 80px;">
                                <i class="material-icons">save</i>
                                Save
                            </button>
                            <a class="btn btn-sm btn-secondary text-white mt-1 mb-1" href="{{ route('administrator.variables.index') }}" style="width: 80px;">
                                <i class="material-icons">reply</i>
                                Cancel
                            </a>
                        </li>
                    </form>
                </ul>
            </div>
        </div>
    </div>
</div>
@endsection

@section('javascript')
<script>
    $(".list-add-button").on("click", function() {
        const list = $(this).parent().prev();
        const listType = list.data("type");
        const lastList = list.children().last();
        const currentListId = parseInt(lastList.data('id')) + 1;

        list.append(`
            <div class="input-group mb-2" data-id="${currentListId}">
                <input type="text" name="${listType}[${currentListId}][name]" class="form-control" placeholder="Name" value="" required>
                <input type="number" step="any" min="0" name="${listType}[${currentListId}][left_point_value]" class="form-control text-right" placeholder="Left Point Value" value="" required>
                <input type="number" step="any" min="0" name="${listType}[${currentListId}][left_midpoint_value]" class="form-control text-right" placeholder="Left Midpoint Value" value="" required>
                <input type="number" step="any" min="0" name="${listType}[${currentListId}][right_midpoint_value]" class="form-control text-right" placeholder="Right Midpoint Value" value="" required>
                <input type="number" step="any" min="0" name="${listType}[${currentListId}][right_point_value]" class="form-control text-right" placeholder="Right Value" value="" required>

                <div class="input-group-append">
                    <button type="button" class="list-destroy-button btn btn-sm btn-danger">Destroy</button>
                </div>
            </div>
        `);
    });

    $(document).on("click", ".list-destroy-button", function() {
        $(this).parent().parent().remove();
    });

    $("#type").on("change", function() {
        if ($(this).val() == "INPUT") {
            $("#column-name").prop("disabled", false);
        } else {
            $("#column-name").prop("disabled", true);
        }
    });
</script>
@endsection