routes/web.php
<?php

use Illuminate\Support\Facades\Route;

$this->settingRole = config("settings.role");

// Route::group([
//     "namespace" => "Home",
//     "as" => "home.",
// ], function () {
//     Route::group([
//         "namespace" => "Dashboards"
//     ], function () {
//         Route::resource("dashboards", "DashboardController")->only(["index"]);
//         Route::group([
//             "as" => "dashboards.",
//         ], function () {
//             Route::get("index", "DashboardController@index")->name("index");
//             Route::get("", "DashboardController@index")->name("index");
//         });
//     });
// });

Route::namespace("Auth")->group(function () {
    Route::get("", "LoginController@showLoginForm")->name("home.dashboards.index");
    Route::get("login", 'LoginController@showLoginForm')->name("login");
    Route::post("login", 'LoginController@login')->name("login");
    Route::post("logout", 'LoginController@logout')->name("logout");
});

Route::middleware(["auth"])->group(function () {
    //Administrator
    Route::group([
        "middleware" => ["role:" . implode("|", $this->settingRole["administrator"])],
        "namespace" => "Administrator",
        "as" => "administrator.",
        "prefix" => "administrator"
    ], function () {
        Route::group([
            "namespace" => "Dashboards",
        ], function () {
            Route::resource("dashboards", "DashboardController")->only(["index"]);
            Route::group([
                "as" => "dashboards.",
            ], function () {
                Route::get("", "DashboardController@index")->name("index");
            });
        });

        Route::group([
            "namespace" => "Profiles",
            "as" => "profile.",
            "prefix" => "profile"
        ], function () {
            Route::get("index", "ProfileController@index")->name("index");
            Route::get("", "ProfileController@index")->name("index");
            Route::put("", "ProfileController@update")->name("update");
            Route::delete("", "ProfileController@destroy")->name("destroy");
            Route::put("password", "ProfileController@updatePassword")->name("update-password");
            Route::put("avatar", "ProfileController@updateAvatar")->name("update-avatar");
        });

        Route::group([
            "middleware" => ["role:" . $this->settingRole["administrator"]["superadmin"]],
        ], function () {
            Route::group([
                "namespace" => "Roles"
            ], function () {
                Route::resource("roles", "RoleController")->except(["show"]);
            });

            Route::group([
                "namespace" => "Permissions"
            ], function () {
                Route::resource("permissions", "PermissionController")->except(["show", "create", "edit"]);
            });
        });

        Route::group([
            "namespace" => "Users"
        ], function () {
            Route::resource("users", "UserController")->except(["show"]);
            Route::group([
                "as" => "users.",
                "prefix" => "users"
            ], function () {
                Route::put("{id}/password", "UserController@updatePassword")->name("update-password");
                Route::put("{id}/status", "UserController@updateStatus")->name("update-status");
                Route::put("{id}/avatar", "UserController@updateAvatar")->name("update-avatar");

                Route::group([
                    "as" => "deleted.",
                    "prefix" => "deleted"
                ], function () {
                    Route::get("index", "UserDeletedController@index")->name("index");
                    Route::get("", "UserDeletedController@index")->name("index");
                    Route::post("{id}/restore", "UserDeletedController@restore")->name("restore");
                });
            });
        });

        Route::group([
            "namespace" => "Variables"
        ], function () {
            Route::resource("variables", "VariableController")->except(["show"]);
        });

        Route::group([
            "namespace" => "Rules"
        ], function () {
            Route::resource("rules", "RuleController")->except(["show"]);
        });

        Route::group([
            "namespace" => "Executes"
        ], function () {
            Route::resource("executes", "ExecuteController")->except(["edit", "update"]);
        });
    });
});

app/Models/Rule.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Rule extends Model
{
    protected $fillable = [
        "variable_assemblage_id"
    ];

    public function conditions()
    {
        return $this->hasMany(RuleCondition::class);
    }

    public function assemblage()
    {
        return $this->belongsTo(VariableAssemblage::class, "variable_assemblage_id", "id");
    }
}

app/Http/Controllers/Administrator/Dashboards/DashboardController.php
<?php

namespace App\Http\Controllers\Administrator\Dashboards;

use App\Http\Controllers\Controller;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;

use App\Models\Person;
use App\Models\Rule;
use App\Models\Variable;

class DashboardController extends Controller
{
    public function __construct()
    {
        $this->settingRole = config("settings.role");

        $this->middleware(function ($request, $next) {
            $this->authUser = auth()->user();
            return $next($request);
        });
    }

    public function index()
    {
        $variables = Variable::all();
        $rules = Rule::all();

        if ($this->authUser->hasRole($this->settingRole["administrator"]["superadmin"])) {
            $permissions = Permission::all();
            $roles = Role::all();
            $people = Person::withTrashed()->orderBy("full_name")->whereHas("user");

            $compact = compact("people", "permissions", "roles");
        } else {
            $people = Person::withTrashed()->orderBy("full_name")->whereHas("user.roles", function ($roles) {
                $roles->where("name", "!=", $this->settingRole["administrator"]["superadmin"]);
            });

            $compact = compact("people", "variables", "rules");
        }

        return view(
            "administrator.dashboards.index",
            $compact
        );
    }
}

app/Http/Controllers/Administrator/Executes/ExecuteController.php
<?php

namespace App\Http\Controllers\Administrator\Executes;

use App\Http\Controllers\Controller;
use App\Models\Rule;
use App\Models\RuleCondition;
use Illuminate\Http\Request;

use App\Models\Variable;

class ExecuteController extends Controller
{
    public function index()
    {
        return redirect()->route(
            "administrator.executes.create"
        );
    }

    public function create()
    {
        $variables = Variable::pluck("name", "id");
        $inputVariables = Variable::whereType("INPUT")->pluck("column_name", "id")->toArray();
        $outputVariables = Variable::whereType("OUTPUT")->pluck("name", "id")->toArray();
        $rules = Rule::all();

        if ($rules->count()) {
            return view(
                "administrator.executes.create",
                compact("variables", "inputVariables", "outputVariables")
            );
        } else {
            abort(404);
        }
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            "file" => "required|mimes:csv,txt",
            "multiplier_result" => "required|numeric",
            "decimal_digit" => "required|numeric",
        ]);

        if ($request->file("file")->getClientOriginalExtension() == "csv") {
            $csvFile = $request->file("file")->getPathname();

            $file = fopen($csvFile, "r");
            $data = $successData = $failedData = [];

            $inputVariables = Variable::whereType("INPUT");
            $outputVariables = Variable::whereType("OUTPUT")->first();
            $tempColumns = fgetcsv($file, 0, ",");
            if (is_array($tempColumns) && count($tempColumns) > $inputVariables->count() && $outputVariables) {
                $inputVariableColumnNames = $inputVariables->pluck("column_name")->toArray();
                $columns["variables"] = [];

                // Take the location of the variable column and separate it from other columns
                foreach ($tempColumns as $key => $tempColumn) {
                    $tempColumn = trim($tempColumn);
                    if ($tempColumn) {
                        if (in_array($tempColumn, $inputVariableColumnNames)) {
                            $columns["variables"][$tempColumn] = $key;
                        } else {
                            $columns["descriptions"][$tempColumn] = $key;
                        }
                    }
                }

                $file = fopen($csvFile, "r");
                $i = 0;
                while (!feof($file)) {
                    $textLine = fgetcsv($file, 0, ",");
                    if ($i > 0 && $textLine && count($textLine) > $inputVariables->count()) {
                        $data[$i] = [
                            "description" => "",
                            "variables" => []
                        ];

                        // Concatenate column contents that are not column variables
                        if ($columns["descriptions"]) {
                            $j = 0;
                            foreach ($columns["descriptions"] as $descriptionKey) {
                                $textLine[$descriptionKey] = trim($textLine[$descriptionKey]);
                                if ($textLine[$descriptionKey]) {
                                    $data[$i]["description"] .= $textLine[$descriptionKey];
                                    if ($j != count($columns["descriptions"]) - 1) {
                                        $data[$i]["description"] .= " - ";
                                    }
                                }
                                $j++;
                            }
                        }

                        if ($columns["variables"]) {
                            foreach ($columns["variables"] as $variableColumnName => $variableKey) {
                                $data[$i]["variables"][$variableColumnName] = [
                                    "input_value" => $textLine[$variableKey] ?? 0
                                ];

                                // Look for membership functions
                                $variable = Variable::whereColumnName($variableColumnName)->first();
                                $data[$i]["variables"][$variableColumnName]["assemblages"] = $variable->assemblages()->where([
                                    ["left_point_value", "<=", $textLine[$variableKey]],
                                    ['right_point_value', '>=', $textLine[$variableKey]]
                                ])->get()->keyBy("id")->toArray();

                                $data[$i]["variables"][$variableColumnName]["id"] = $variable->id;
                                $data[$i]["variables"][$variableColumnName]["name"] = $variable->name;
                                $data[$i]["variables"][$variableColumnName]["column_name"] = $variable->column_name;

                                // Calculate the implication value of each set of variables
                                $assemblages = $variable->assemblages()->get();
                                $implications = $data[$i]["variables"][$variableColumnName]["assemblages"];
                                foreach ($assemblages as $assemblage) {
                                    if (array_key_exists($assemblage->id, $data[$i]["variables"][$variableColumnName]["assemblages"])) {
                                        $inputValue =  $data[$i]["variables"][$variableColumnName]["input_value"];
                                        if ($assemblage->left_point_value <= $inputValue && $assemblage->left_midpoint_value >= $inputValue) {
                                            if ($assemblage->left_point_value == $assemblage->left_midpoint_value) {
                                                $implications[$assemblage->id]["value"] = 1;
                                            } else {
                                                $implications[$assemblage->id]["value"] = ($inputValue - $assemblage->left_point_value) / ($assemblage->left_midpoint_value - $assemblage->left_point_value);
                                            }
                                        } else if ($assemblage->left_midpoint_value <= $inputValue && $assemblage->right_midpoint_value >= $inputValue) {
                                            $implications[$assemblage->id]["value"] = 1;
                                        } else if ($assemblage->right_midpoint_value <= $inputValue && $assemblage->right_point_value >= $inputValue) {
                                            if ($assemblage->right_point_value == $assemblage->right_midpoint_value) {
                                                $implications[$assemblage->id]["value"] = 1;
                                            } else {
                                                $implications[$assemblage->id]["value"] = ($assemblage->right_point_value - $inputValue) / ($assemblage->right_point_value - $assemblage->right_midpoint_value);
                                            }
                                        } else {
                                            $implications[$assemblage->id]["value"] = 0;
                                        }
                                    }
                                }

                                $data[$i]["variables"][$variableColumnName]["assemblages"] = $implications;
                            }

                            // Create all possible rules from a variable set
                            $variables = $data[$i]["variables"];
                            $j = 0;
                            $assemblageIds = [];
                            foreach ($variables as $variableKey => $variable) {
                                $assemblageIdsTemporaries = [];
                                foreach ($variable["assemblages"] as $assemblage) {
                                    if ($j === 0) {
                                        $assemblageIds[] = [$assemblage["id"]];
                                    } else {
                                        foreach ($assemblageIds as $key => $assemblageId) {
                                            array_push($assemblageId, $assemblage["id"]);
                                            $assemblageIdsTemporaries[] = $assemblageId;
                                        }
                                    }
                                }

                                if ($j !== 0) {
                                    $assemblageIds = $assemblageIdsTemporaries;
                                }
                                $j++;
                            }

                            $rules = Rule::with(["assemblage.variable", "conditions.assemblage.variable"])->get();
                            $is_founded = false;
                            $multiplicationResult = $increaseInYield = 0;
                            foreach ($rules as $rule) {
                                // Look for rules that are already in the database
                                foreach ($assemblageIds as $assemblageId) {
                                    $ruleConditionsCountTemp = RuleCondition::whereRuleId($rule->id)->whereIn("variable_assemblage_id", $assemblageId)->count();
                                    if ($ruleConditionsCountTemp >= count($assemblageId)) {
                                        $ruleTemp = $rule->toArray();
                                        $is_founded = true;
                                    }
                                }

                                // If a rule is found
                                if ($is_founded) {
                                    $conditionValue = [];
                                    // Takes the implication value of each set of variables based on the found rules

resources/views/administrator/rules/index.blade.php
@extends('administrator.layouts.template')

@section('css')
<link href="https://cdn.datatables.net/1.10.22/css/dataTables.bootstrap4.min.css" rel="stylesheet">

<style>
    .dataTables_length,
    .dataTables_filter,
    .dataTables_info,
    .dataTables_paginate {
        margin-left: 1.1rem !important;
        margin-right: 1.1rem !important;
    }

    .dataTables_length,
    .dataTables_info {
        text-align: left;
    }
</style>
@endsection

@section('content')
@if ($message = session()->get("success"))
<div class="alert alert-success alert-dismissible fade show mb-0" role="alert">
    <button type="button" class="close h-100" data-dismiss="alert" aria-label="Close" style="outline: none;">
        <span aria-hidden="true">×</span>
    </button>
    <i class="fa fa-check mx-2"></i>
    <strong>{{ $message }}</strong>
</div>
@endif

<div class="main-content-container container-fluid px-4">
    <!-- Page Header -->
    <div class="page-header row no-gutters mb-4"></div>
    <!-- End Page Header -->

    <div class="row">
        <div class="col">
            <div class="card card-small mb-4">
                <div class="card-header border-bottom">
                    <h6 class="float-left m-0 mt-1">Rules</h6>
                    <div class="float-right">
                        <a href="{{ route('administrator.rules.create') }}" class="btn btn-sm btn-success">
                            <i class="material-icons">add</i>
                            Create
                        </a>
                    </div>
                </div>

                <div class="card-body p-0 pt-3 pb-2 table-responsive">
                    <table id="table" class="table table-hover w-100">
                        <thead class="bg-light">
                            <tr class="text-center">
                                <th scope="col" class="border-0" style="width: 50px;">#</th>
                                <th scope="col" class="border-0">Rule</th>
                                <th scope="col" class="border-0" style="width: 180px; min-width: 180px;">Actions</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<div hidden>
    <form id="option-form" method="POST">
        @csrf
        <input type="hidden" id="option-method" name="_method" value="POST">
    </form>
</div>
@endsection

@section('javascript')
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.22/js/dataTables.bootstrap4.min.js"></script>

<script>
    const handleDestroy = id => {
        swal({
                title: "Are you sure?",
                text: "Once deleted, you will not be able to recover this item!",
                icon: "warning",
                buttons: true,
                dangerMode: true,
            })
            .then(willDelete => {
                if (willDelete) {
                    $("#option-form").attr("action", `{{ route('administrator.rules.index') }}/${id}`);
                    $("#option-method").val("DELETE");
                    $("#option-form").submit();
                }
            });
    }

    $("#table").DataTable({
        responsive: true,
        language: {
            paginate: {
                previous: "‹",
                next: "›"
            }
        },
        processing: true,
        serverSide: true,
        ajax: {
            url: "{{ request()->url() }}",
            headers: {
                "X-CSRF-TOKEN": $('meta[name="csrf-token"]').attr('content')
            }
        },
        columns: [{
            data: "DT_RowIndex",
            searchable: false
        }, {
            data: "column_rule"
        }, {
            data: "column_actions",
            orderable: false,
            searchable: false
        }],
        order: [
            [0, "asc"]
        ],
        createdRow: function(row, data, indice) {
            $(row).data("id", data.id);

            $('td:eq(0)', row).addClass("align-middle text-center");
            $('td:eq(1)', row).addClass("align-middle");
            $('td:eq(2)', row).addClass("align-middle");
        }
    });
</script>
@endsection